# Generated by Django 4.2.11 on 2024-05-13 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="race",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_current", models.BooleanField(blank=True, null=True)),
                ("distance", models.IntegerField()),
                ("laps", models.IntegerField()),
                ("start_time", models.TimeField(blank=True, null=True)),
                ("end_time", models.TimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="runners",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("number", models.IntegerField()),
                ("type", models.CharField(blank=True, max_length=64, null=True)),
                ("notes", models.CharField(blank=True, max_length=512, null=True)),
                (
                    "race",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="tracker.race"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="laps",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time", models.DateField(auto_now_add=True)),
                ("lap", models.IntegerField()),
                (
                    "runner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tracker.runners",
                    ),
                ),
            ],
        ),
    ]
