# Generated by Django 5.0.6 on 2024-05-18 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_race_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laps',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='race',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='race',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
