# Generated by Django 5.0.6 on 2024-05-19 18:53

from django.db import migrations, models
import datetime


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_alter_runners_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='laps',
            name='average_speed',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='laps',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(0)),
            preserve_default=False,
        ),
    ]
