# Generated by Django 5.0.6 on 2024-05-19 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_laps_average_speed_laps_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laps',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
