# Generated by Django 5.0.6 on 2024-05-19 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_alter_laps_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='runners',
            name='race_completed',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
