# Generated by Django 5.0.6 on 2024-05-19 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_runners_race_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='runners',
            name='total_race_time',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
