# Generated by Django 5.0.6 on 2024-05-19 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_runners_total_race_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='runners',
            name='race_avg_speed',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
