# Generated by Django 5.0.6 on 2024-05-24 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0010_runners_race_avg_speed'),
    ]

    operations = [
        migrations.AddField(
            model_name='runners',
            name='place',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
