# Generated by Django 5.0.6 on 2024-05-24 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0011_runners_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runners',
            name='race_avg_speed',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
