# Generated by Django 5.0.6 on 2024-05-24 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0012_alter_runners_race_avg_speed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laps',
            name='average_speed',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
