# Generated by Django 5.0.6 on 2024-05-24 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0013_alter_laps_average_speed'),
    ]

    operations = [
        migrations.AddField(
            model_name='runners',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=50, null=True),
        ),
    ]
