# Generated by Django 5.1.3 on 2025-01-28 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0014_runners_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runners',
            name='type',
            field=models.CharField(blank=True, choices=[('running', 'Running'), ('walking', 'Walking')], max_length=64, null=True),
        ),
    ]
