# Generated by Django 5.1.3 on 2025-01-29 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0015_alter_runners_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='status',
            field=models.CharField(choices=[('signup_open', 'Sign Up Open'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='completed', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='runners',
            name='age',
            field=models.CharField(choices=[('0-12', '0-12'), ('12-17', '12-17'), ('18-34', '18-34'), ('35-49', '35-49'), ('50+', '50+')], default='0-12', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='runners',
            name='email',
            field=models.EmailField(default='placeholder@example.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='runners',
            name='shirt_size',
            field=models.CharField(blank=True, choices=[('Extra Small', 'Extra Small'), ('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large'), ('Extra Large', 'Extra Large'), ('XXL', 'XXL')], max_length=64, null=True),
        ),
    ]
