# Generated by Django 5.1.3 on 2025-01-31 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0018_race_entry_fee_race_date_alter_race_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runners',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
