# Generated by Django 5.1.5 on 2025-02-05 04:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0019_alter_runners_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='race',
            name='is_current',
        ),
        migrations.AddField(
            model_name='laps',
            name='avgerage_pace',
            field=models.DurationField(default=datetime.timedelta(seconds=90)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='runners',
            name='race_avg_pace',
            field=models.DurationField(default=datetime.timedelta(seconds=90)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='runners',
            name='rfid_tag',
            field=models.BinaryField(blank=True, max_length=496, null=True),
        ),
    ]
