# Generated by Django 5.1.5 on 2025-02-08 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0021_alter_race_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='max_runners',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='race',
            name='number_start',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
