# Generated by Django 5.1.5 on 2025-02-08 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0022_race_max_runners_race_number_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runners',
            name='shirt_size',
            field=models.CharField(choices=[('Kids XS', 'Kids XS'), ('Kids S', 'Kids S'), ('Kids M', 'Kids M'), ('Kids L', 'Kids L'), ('Extra Small', 'Extra Small'), ('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large'), ('XL', 'XL'), ('XXL', 'XXL')], max_length=64),
        ),
    ]
