# Generated by Django 5.1.5 on 2025-02-08 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0024_alter_runners_race_avg_pace'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='scheduled_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
