# Generated by Django 5.1.5 on 2025-02-09 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0025_race_scheduled_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='notes',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
