# Generated by Django 5.1.5 on 2025-02-10 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0028_alter_banner_background_color_alter_banner_subtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
