# Generated by Django 5.1.5 on 2025-02-10 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0029_alter_banner_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
