# Generated by Django 5.1.5 on 2025-02-18 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0031_apikey'),
    ]

    operations = [
        migrations.RenameField(
            model_name='laps',
            old_name='avgerage_pace',
            new_name='average_pace',
        ),
    ]
