# Generated by Django 5.1.5 on 2025-02-20 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0032_rename_avgerage_pace_laps_average_pace'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='min_lap_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
