# Generated by Django 5.1.5 on 2025-02-23 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0033_race_min_lap_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='pages',
            field=models.CharField(choices=[('all', 'All Pages'), ('signup', 'Sign Up Page'), ('results', 'Results Page'), ('countdown', 'Countdown Page')], default='all', max_length=20),
        ),
        migrations.AddField(
            model_name='race',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='runners',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
