# Generated by Django 5.1.5 on 2025-03-15 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0034_banner_pages_race_logo_runners_email_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='all_emails_sent',
            field=models.BooleanField(default=False),
        ),
    ]
