# Generated by Django 5.1.5 on 2025-03-16 01:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0035_race_all_emails_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='min_lap_time',
            field=models.DurationField(default=datetime.timedelta(seconds=90)),
            preserve_default=False,
        ),
    ]
