# Generated by Django 6.0 on 2026-02-04 03:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0036_alter_race_min_lap_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='RfidTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_number', models.IntegerField(help_text='Number used when auto-assigning (same as runner number)', unique=True)),
                ('rfid_hex', models.CharField(help_text='Hex string from the physical RFID tag', max_length=512)),
            ],
            options={
                'verbose_name': 'RFID tag',
                'verbose_name_plural': 'RFID tags',
                'ordering': ['tag_number'],
            },
        ),
        migrations.RemoveField(
            model_name='runners',
            name='rfid_tag',
        ),
        migrations.AddField(
            model_name='runners',
            name='tag',
            field=models.ForeignKey(blank=True, help_text='Reusable RFID tag; auto-assigned by tag_number when assigning runner numbers', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runner_assignments', to='tracker.rfidtag'),
        ),
    ]
