# Generated by Django 6.0 on 2026-02-04 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0037_rfidtag_remove_runners_rfid_tag_runners_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paypal_enabled', models.BooleanField(default=False, help_text='When on, signup redirects to PayPal with entry fee; when off, signup goes to success page only.')),
                ('paypal_business_email', models.EmailField(blank=True, help_text='PayPal email that receives entry fee donations.', max_length=254)),
                ('paypal_sandbox', models.BooleanField(default=False, help_text='Use PayPal Sandbox for testing. Turn off for live payments.')),
            ],
            options={
                'verbose_name': 'Site settings',
                'verbose_name_plural': 'Site settings',
            },
        ),
        migrations.AddField(
            model_name='runners',
            name='paid',
            field=models.BooleanField(default=False, help_text='True when PayPal donation/payment completed'),
        ),
    ]
