# Generated by Django 6.0 on 2026-02-04 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0038_sitesettings_runners_paid'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSendJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sending', 'Sending'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='queued', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('error_message', models.TextField(blank=True)),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.race')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
