# Generated by Django 6.0 on 2026-02-04 15:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0039_emailsendjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='runners',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='runners',
            name='signup_confirmation_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='signup_confirmation_timeout_minutes',
            field=models.PositiveIntegerField(default=15, help_text='Minutes to wait for PayPal confirmation before sending signup confirmation email. If unpaid after this, email is sent with a link to pay.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_base_url',
            field=models.URLField(blank=True, help_text='Base URL of this site (e.g. https://example.com). Used for pay-later links in signup confirmation emails.', max_length=500),
        ),
    ]
