# Generated by Django 6.0 on 2026-02-07 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0041_runners_gender_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='runners',
            name='chip_time',
            field=models.DurationField(blank=True, help_text='Chip time: from first crossing (lap 0) or race start to finish', null=True),
        ),
        migrations.AlterField(
            model_name='runners',
            name='total_race_time',
            field=models.DurationField(blank=True, help_text='Gun time: from race start to finish', null=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='signup_confirmation_timeout_minutes',
            field=models.PositiveIntegerField(default=15, help_text='Send signup confirmation to runners who have not received one and signed up more than this many minutes ago (or have already paid). The background worker (same as race emails) uses this value.'),
        ),
    ]
