# Generated by Django 6.0 on 2026-02-07

from django.db import migrations, models


def backfill_banner_pages(apps, schema_editor):
    """Set new show_on_* fields from old pages CharField."""
    Banner = apps.get_model('tracker', 'Banner')
    for b in Banner.objects.all():
        old = getattr(b, 'pages', 'all') or 'all'
        if old == 'all':
            b.show_on_home = True
            b.show_on_signup = True
            b.show_on_results = True
            b.show_on_countdown = True
        elif old == 'signup':
            b.show_on_signup = True
        elif old == 'results':
            b.show_on_results = True
        elif old == 'countdown':
            b.show_on_countdown = True
        b.save(update_fields=['show_on_home', 'show_on_signup', 'show_on_results', 'show_on_countdown'])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0042_runners_chip_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='show_on_home',
            field=models.BooleanField(default=False, help_text='Show on the public home / race list page'),
        ),
        migrations.AddField(
            model_name='banner',
            name='show_on_signup',
            field=models.BooleanField(default=False, help_text='Show on the sign-up page'),
        ),
        migrations.AddField(
            model_name='banner',
            name='show_on_results',
            field=models.BooleanField(default=False, help_text='Show on results / completed race pages'),
        ),
        migrations.AddField(
            model_name='banner',
            name='show_on_countdown',
            field=models.BooleanField(default=False, help_text='Show on countdown / upcoming race page'),
        ),
        migrations.RunPython(backfill_banner_pages, noop_reverse),
        migrations.RemoveField(
            model_name='banner',
            name='pages',
        ),
    ]
