# Generated by Django 6.0 on 2026-02-07 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0043_banner_page_checkboxes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='paypal_business_email',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='paypal_sandbox',
        ),
    ]
