# Generated by Django 6.0 on 2026-02-07 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0044_remove_paypal_email_sandbox_from_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailsendjob',
            name='unpaid_reminder',
            field=models.BooleanField(default=False, help_text='When True, send only to unpaid runners and append payment link to each email.'),
        ),
    ]
