# Generated by Django 6.0 on 2026-02-08 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0045_emailsendjob_unpaid_reminder'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfidtag',
            name='name',
            field=models.CharField(blank=True, help_text='Optional label for this tag', max_length=255),
        ),
    ]
