# Generated by Django 6.0 on 2026-02-08 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0046_rfidtag_name'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='runners',
            constraint=models.UniqueConstraint(condition=models.Q(('tag__isnull', False)), fields=('race', 'tag'), name='unique_race_tag'),
        ),
    ]
