# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0047_unique_race_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='runners',
            name='send_signup_confirmation',
            field=models.BooleanField(
                default=False,
                help_text='If True, runner is eligible for signup confirmation email (set for signup-form signups, or when "Send confirmation email" is checked on runner page).',
            ),
        ),
        migrations.AlterField(
            model_name='runners',
            name='send_signup_confirmation',
            field=models.BooleanField(
                default=True,
                help_text='If True, runner is eligible for signup confirmation email (set for signup-form signups, or when "Send confirmation email" is checked on runner page).',
            ),
        ),
    ]
