# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0048_runners_send_signup_confirmation'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='archived',
            field=models.BooleanField(
                default=False,
                help_text='If True, hide this race everywhere except on the View Past Races page.',
            ),
        ),
        migrations.AddField(
            model_name='race',
            name='hidden_from_past_races',
            field=models.BooleanField(
                default=False,
                help_text='If True, hide this race on the View Past Races page as well.',
            ),
        ),
    ]
