# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0049_race_archived_hidden_from_past_races'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='background_image',
            field=models.URLField(
                blank=True,
                help_text='URL of a background image for all pages (e.g. https://example.com/image.jpg). Leave blank to use the default logo background.',
                max_length=500,
            ),
        ),
    ]
