# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0050_sitesettings_background_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='background_image_file',
            field=models.ImageField(
                blank=True,
                help_text='Upload a background image (used instead of URL if set).',
                null=True,
                upload_to='site/',
            ),
        ),
    ]
