# Generated by Django 6.0 on 2026-02-16 04:44

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0051_sitesettings_background_image_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='background_color',
            field=models.CharField(default='#ffffff', max_length=30, validators=[django.core.validators.RegexValidator(message='Background color must be a valid hex color (e.g. #ff0000).', regex='^#[0-9a-fA-F]{6}$')]),
        ),
        migrations.AlterField(
            model_name='race',
            name='Entry_fee',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='race',
            name='distance',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='race',
            name='laps_count',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='race',
            name='max_runners',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.CreateModel(
            name='PayPalOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(db_index=True, help_text='PayPal order ID', max_length=64, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Expected payment amount', max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('status', models.CharField(default='CREATED', help_text='Order status from PayPal', max_length=32)),
                ('capture_id', models.CharField(blank=True, help_text='PayPal capture/transaction ID', max_length=64)),
                ('payer_email', models.EmailField(blank=True, max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('captured_at', models.DateTimeField(blank=True, null=True)),
                ('runner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paypal_orders', to='tracker.runners')),
            ],
            options={
                'verbose_name': 'PayPal order',
                'verbose_name_plural': 'PayPal orders',
                'ordering': ['-created_at'],
            },
        ),
    ]
