from django.urls import path

from .views import (
    race_start_view,
    race_overview,
    runner_stats,
    race_signup,
    signup_success,
    paypal_return,
    paypal_cancel,
    paypal_ipn,
    site_settings_view,
    select_race,
    view_shirt_sizes,
    select_race_for_runners,
    show_runners,
    add_runner,
    edit_runner,
    rfid_tags_list,
    RaceAdd,
    RaceEdit,
    ListRaces,
    assign_numbers,
    generate_api_key,
    record_lap,
    update_race_time,
    update_rfid,
    get_available_races,
    mark_runner_finished,
    completed_races_selection, 
    get_completed_race_overview,
    email_list_view,
    select_race_for_report,
    generate_runner_pdf_report,
    GenerateRaceReportView,
)

app_name = 'tracker'
urlpatterns = [
    path('', race_overview, name='race-overview'),
    path('race_add/', RaceAdd.as_view(), name='race-add'),
    path('race_edit/<int:pk>/', RaceEdit.as_view(), name='edit-race'),
    path('list_races/', ListRaces.as_view(), name='list-races'),
    path('race-start', race_start_view, name='race-start'),
    path('runner-stats', runner_stats, name='runner-stats'),
    path('signup/', race_signup, name='race-signup'),
    path('signup_success/<int:pk>', signup_success, name='signup-success'),
    path('paypal/return/', paypal_return, name='paypal-return'),
    path('paypal/cancel/', paypal_cancel, name='paypal-cancel'),
    path('paypal/ipn/', paypal_ipn, name='paypal-ipn'),
    path('settings/', site_settings_view, name='site-settings'),
    path('select_race/', select_race, name='select_race'),
    path('shirt_view/<int:pk>/', view_shirt_sizes, name='view_shirts'),
    path('runners_view/<int:pk>/', show_runners, name='view_runners'),
    path('api/add-runner/', add_runner, name='add_runner'),
    path('api/edit-runner/', edit_runner, name='edit_runner'),
    path('select_race_runners', select_race_for_runners, name='select_race_runners'),
    path('assign_numbers/', assign_numbers, name='assign_numbers'),
    path('rfid-tags/', rfid_tags_list, name='rfid_tags_list'),
    path('mark_runner_finished/', mark_runner_finished, name='mark_runner_finished'),
    path('race_report/<int:race_id>/<int:runner_id>/', GenerateRaceReportView.as_view(), name='race_report'),
    path('completed_races_selection/', completed_races_selection, name='completed_races_selection'),
    path('get_completed_race_overview/<int:race_id>/', get_completed_race_overview, name='get_completed_race_overview'),
    path('email_list/', email_list_view, name='email_list'),
    path('select-race/', select_race_for_report, name='select_race_report'),
    path('generate-pdf/', generate_runner_pdf_report, name='generate_runner_pdf'),
    # API endpoints
    path('generate-api-key/', generate_api_key, name='generate-api-key'),
    path('api/record-lap/', record_lap, name='api-record-lap'),
    path('api/update-race-time/', update_race_time, name='api-update-race-time'),
    path('api/update-rfid/', update_rfid, name='api-update-rfid'),
    path('api/available-races/', get_available_races, name='api-available-races'),

]
